name: Deploy to GitHub Pages

on:
  push:
    branches: ['dev', 'main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true


jobs:
  deploy:
    environment:
      name: github-pages-dev
      url: ${{ github.ref == 'refs/heads/dev' && format('https://{0}.github.io/{1}/dev', github.repository_owner, github.event.repository.name) || format('https://{0}.github.io/{1}/', github.repository_owner, github.event.repository.name) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set build mode based on the branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "Setting NODE_ENV=development"
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "Setting BUILD_MODE=development"
            echo "BUILD_MODE=development" >> $GITHUB_ENV
          else
            echo "Setting NODE_ENV=production"
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "Setting BUILD_MODE=production"
            echo "BUILD_MODE=production" >> $GITHUB_ENV
          fi

      # - name: Run predeploy
      #   run: npm run predeploy

      - name: Log BUILD_MODE
        run: echo "BUILD_MODE=$BUILD_MODE"

      - name: Run predeploy
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            npm run build:dev
          else
            npm run build:prod
          fi
        env:
          BUILD_MODE: ${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up GH_TOKEN for release
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Release
        run: npm run release

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: './dist'  # Only specify the path to the build output
      #     destination_dir: ${{ github.ref == 'refs/heads/dev' && 'dev' || '' }}

      - name: Upload artifact for production
        if: github.ref == 'refs/heads/main'  # Only run this if the branch is main
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Upload production build
          destination_dir: ''

      - name: Upload artifact for development
        if: github.ref == 'refs/heads/dev'  # Only run this if the branch is dev
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/dev'  # Upload dev build
          destination_dir: 'dev'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Log deployment URL
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "Deployment URL: format('https://{0}.github.io/{1}/dev', github.repository_owner, github.event.repository.name)/dev"
          else
            echo "Deployment URL: format('https://{0}.github.io/{1}/dev', github.repository_owner, github.event.repository.name)/"
          fi

