name: Deploy to GitHub Pages Prod

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install
        run: npm ci

      - name: Release changelog/version
        if: github.ref == 'refs/heads/main'
        run: npm run release

      - name: Build
        run: npm run build

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/dev
          target-folder: dev
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy main
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}