name: Deploy to GitHub Pages

on:
  push:
    branches: ['dev']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ github.ref == 'refs/heads/dev' && 'https://${{ github.repository_owner }}.github.io/${{ github.repository.split('/')[1] }}/dev' || 'https://${{ github.repository_owner }}.github.io/${{ github.repository.split('/')[1] }}/' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set build mode based on the branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "Setting NODE_ENV=development"
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "Setting BUILD_MODE=development"
            echo "BUILD_MODE=development" >> $GITHUB_ENV
          else
            echo "Setting NODE_ENV=production"
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "Setting BUILD_MODE=production"
            echo "BUILD_MODE=production" >> $GITHUB_ENV
          fi

      - name: Run predeploy
        run: npm run predeploy

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up GH_TOKEN for release
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Release
        run: npm run release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Only specify the path to the build output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Log the dynamic URL based on the branch (dev or main)
      - name: Log deployment URL
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "Deployment URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/dev"
          else
            echo "Deployment URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
          fi
