name: Deploy and Release

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    types: [labeled]  # Trigger on PR labeling

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Only continue if the PR is labeled with 'release'
      - name: Check PR Label
        if: contains(github.event.pull_request.labels.*.name, 'release')
        run: echo "PR is labeled with 'release', proceeding with deploy and release tasks."

      - name: Install dependencies
        run: npm install

      - name: Run deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
