name: Deploy to GitHub Pages (dev)

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (if using a static site generator like Gatsby, Jekyll, etc.)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Adjust this according to your build process

    - name: Deploy to GitHub Pages (dev)
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch that GitHub Pages will use
        folder: build     # The folder containing the build output (adjust as necessary)
        target_folder: dev # Subfolder where dev version will be hosted
        token: ${{ secrets.GITHUB_TOKEN }}  # Token to authenticate GitHub Pages deployment
